const BUTTERCUP_COLOUR_RGB = [0, 183, 172];
const FIGURE_COLOUR_RGB = [252, 73, 97];
const OPTION_COLOUR_RGB = [61, 144, 252];

module.exports = {
    BUTTERCUP_COLOUR_RGB,
    FIGURE_COLOUR_RGB,
    OPTION_COLOUR_RGB
};
